# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='action',
            field=models.CharField(max_length=20, verbose_name='get/post支持'),
        ),
        migrations.AlterField(
            model_name='proxy',
            name='http',
            field=models.CharField(max_length=20, verbose_name='类型: HTTP/HTTPS'),
        ),
    ]
