# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20160703_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxy',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP地址'),
        ),
    ]
